### PR TITLE
Adding support for go1.17

### LINKED ISSUE #629: source/iofs/iofs.go doesn't support go1.17
**Describe the Bug**
Builds don't work when using the file driver using go1.17 due to build constraint in the file.

**Steps to Reproduce**
1. use a file migration
2. attempt to build using go 1.17
3. See error `golang-migrate/migrate/v4/source/file/file.go:17:2: undefined: iofs.PartialDriver`

**Expected Behavior**
It should build as go1.17 is supported in the rest of the repo (that I can see)

**Migrate Version**
e.g. v4.15.0

**Loaded Source Drivers**
e.g. file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
e.g. postgres, postgresql, mysql, sqlite

**Go Version**
e.g. go version go1.17.1 darwin/amd64

### PR DESCRIPTION
**Pull request by theflyingcodr**
Fixes https://github.com/golang-migrate/migrate/issues/629

This offers one fix, however, if go1.15 and below support are now dropped from migrate I can simply remove the build tag, let me know.

### CODE REVIEW

**Comment by dhui** [comment]
We should support Go 1.18 (and 1.17) and drop support for older versions.
CC @Fontinalis

**Comment by Fontinalis** [comment]
> We should support Go 1.18 (and 1.17) and drop support for older versions. CC @Fontinalis

@dhui I was thinking about the same, just didn't leave a comment / note about it, that's why I added to the next milestone.

**Comment by Fontinalis** [comment]
Uff, time flies.. ✈️  and we are also long past go1.17. 

Thank you @theflyingcodr for originally putting the work into this - I'm going to close this for now.

**Comment by theflyingcodr** [comment]
> Uff, time flies.. ✈️  and we are also long past go1.17. 
> 
> Thank you @theflyingcodr for originally putting the work into this - I'm going to close this for now. 

Hah I don't even remember doing this
