### ISSUE TITLE
 undefined: iofs.PartialDriver error on mysql tag

### ISSUE THREAD

**Issue by cemezgin** [golang-migrate/migrate#622]
**Describe the Bug**
I am getting an error when I try to get mysql tag via go get.

**Steps to Reproduce**
1. I have this command in my Dockerfile `RUN go get -tags 'mysql' -u github.com/golang-migrate/migrate/cmd/migrate`  
2. When I build it, see the error

**Go Version**
go version go1.13.15 linux/amd64

**Stacktrace**
```
> [8/8] RUN go get -tags 'mysql' -u github.com/golang-migrate/migrate/cmd/migrate:                                                                                                                                                     
#12 6.997 # github.com/golang-migrate/migrate/source/file
#12 6.997 ../../golang-migrate/migrate/source/file/file.go:17:2: undefined: iofs.PartialDriver
```

**Comment by robovarga** [comment]
Same problem

> **Go Version**
> go version go1.15.1 linux/amd64

**Comment by djhworld** [comment]
The iofs package has build constraints put in place to only build on go1.16+ 

https://github.com/golang-migrate/migrate/blob/master/source/iofs/iofs.go#L2

To resolve you can upgrade to go 1.16+ and also use the command highlighted in https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#unversioned

**Comment by Fontinalis** [comment]
As @djhworld said and pointed out, the minimum version for Go is now 1.16. Using the mentioned solution is a great way to resolve the issue. 

On the same note, `v4.15.0` was just released with the mentioned changes included.
